version: '3'

services:
  app:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: >
      sh -c "yarn install &&
             yarn run dev"